# Generated by Django 4.0 on 2022-02-14 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empID', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=122, null=True)),
                ('Designation', models.CharField(max_length=122, null=True)),
                ('contact', models.CharField(max_length=13, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('joiningDate', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
