# Generated by Django 4.0 on 2022-02-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empdetail',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='empdetail',
            old_name='Designation',
            new_name='designation',
        ),
        migrations.AddField(
            model_name='empdetail',
            name='middlename',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
