# Generated by Django 4.0 on 2022-02-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee', '0003_empexp_empedu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpEdu',
            new_name='EmpEducation',
        ),
        migrations.RenameModel(
            old_name='EmpExp',
            new_name='EmpExperience',
        ),
    ]
