# Generated by Django 4.0 on 2022-02-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_empedu_empeducation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdetail',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empdetail',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empdetail',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='empdetail',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empdetail',
            name='zip',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
