# Generated by Django 4.0 on 2022-02-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_empdetail_address_empdetail_city_empdetail_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetail',
            name='zip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
