# Generated by Django 4.0 on 2022-02-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_empdetail_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetail',
            name='zip',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
