# Generated by Django 4.0 on 2022-03-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee', '0007_alter_empdetail_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.PositiveIntegerField(default=0)),
                ('DA', models.PositiveIntegerField(default=0)),
                ('HRA', models.PositiveIntegerField(default=0)),
                ('medical', models.PositiveIntegerField(default=0)),
                ('transport', models.PositiveIntegerField(default=0)),
                ('reimbursement', models.PositiveIntegerField(default=0)),
                ('pf', models.PositiveIntegerField(default=0)),
                ('esi', models.PositiveIntegerField(default=0)),
                ('pt', models.PositiveIntegerField(default=0)),
                ('tds', models.PositiveIntegerField(default=0)),
                ('lwf', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
