# Generated by Django 4.0 on 2022-03-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_emppayroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('basic', models.PositiveIntegerField(default=0)),
                ('DA', models.PositiveIntegerField(default=0)),
                ('HRA', models.PositiveIntegerField(default=0)),
                ('medical', models.PositiveIntegerField(default=0)),
                ('transport', models.PositiveIntegerField(default=0)),
                ('reimbursement', models.PositiveIntegerField(default=0)),
                ('pf', models.PositiveIntegerField(default=0)),
                ('esi', models.PositiveIntegerField(default=0)),
                ('pt', models.PositiveIntegerField(default=0)),
                ('tds', models.PositiveIntegerField(default=0)),
                ('lwf', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
