# Generated by Django 4.0 on 2022-03-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_emppayroll_grade_class_alter_emppayroll_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emppayroll',
            name='grade_class',
            field=models.ForeignKey(default='Manager', on_delete=django.db.models.deletion.CASCADE, related_name='grade_class', to='employee.grade'),
        ),
    ]
