# Generated by Django 4.0 on 2022-03-13 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_emppayroll_grade_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emppayroll',
            name='grade_class',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='grade_class', to='employee.grade'),
        ),
    ]
