# Generated by Django 4.0 on 2022-04-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_emppayroll_da_alter_emppayroll_hra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emppayroll',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='emppayroll',
            name='tot_ded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='emppayroll',
            name='tot_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
